FROM floydhub/dl-base:3.0.0-gpu-py2.18
MAINTAINER Russell labs "contact@russellcloud.cn"
ARG WhlFN=paddlepaddle_gpu-0.11.1a2-cp27-cp27mu-linux_x86_64.whl
COPY $WhlFN /
RUN pip --default-timeout=1000 install $WhlFN && rm $WhlFN