FROM floydhub/dl-base:3.0.0-py2.18
MAINTAINER Floyd Labs "support@floydhub.com"
# doc: https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile
ARG CAFFE_VERSION=2.0

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgflags-dev \
    libgtest-dev \
    libiomp-dev \
    libleveldb-dev \
    liblmdb-dev \
    libopencv-dev \
    libopenmpi-dev \
    libsnappy-dev \
    openmpi-bin \
    openmpi-doc \
    python-numpy \
    python-pydot \
    python-setuptools \
    python-scipy \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    flask \
    graphviz \
    jupyter \
    matplotlib \
    pydot \
    python-nvd3 \
    pyyaml \
    requests \
    scikit-image \
    scipy \
    setuptools \
    tornado
# for Ubuntu 14.04
# sudo apt-get install -y --no-install-recommends libgflags2
# for Ubuntu 16.04
#RUN apt-get install -y --no-install-recommends libgflags-dev

# upgrade eigen to v3.3.0+
RUN wget -O eigen.3.3.4.tar.gz http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz \
    && tar xzvf eigen.3.3.4.tar.gz \
    && rm -rf /usr/include/eigen3/ eigen.3.3.4.tar.gz\
    && mv `ls|grep eigen-eigen` eigen3  \
    && mv eigen3 /usr/include/

### Clone & Build ###
# This will build Caffe2 in an isolated directory so that Caffe2 source is
# unaffected

# This configures the build and finds which libraries it will include in the
# Caffe2 installation. The output of this command is very helpful in debugging

# This actually builds and installs Caffe2 from makefiles generated from the
# above configuration step

RUN git clone --recursive https://github.com/caffe2/caffe2.git
RUN cd caffe2 \
    && mkdir build && cd build  \
    && cmake .. \
    -DUSE_CUDA=OFF \
    -DUSE_NNPACK=OFF \
    -DUSE_ROCKSDB=OFF \
    && make -j"$(nproc)" install  \
    && ldconfig \
    && make clean \
    && cd .. \
    && rm -rf build

ENV PYTHONPATH /usr/local

